# Generated by Django 3.2.21 on 2023-11-02 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0003_alter_commentsmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group_chat.imagemodel'),
        ),
    ]
