# Generated by Django 3.2.21 on 2023-11-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_chat', '0004_alter_commentsmodel_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentsmodel',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
