# Generated by Django 3.2.21 on 2023-10-13 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=254)),
                ('comment', models.TextField()),
                ('comment_post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_created', to='home.channelposts')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postcomments_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
