# Generated by Django 3.2.21 on 2023-10-23 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0005_auto_20231021_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmodel',
            name='description',
        ),
        migrations.CreateModel(
            name='EmojiModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji_url', models.URLField()),
                ('count', models.PositiveIntegerField(default=1)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emojimodel_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
