# Generated by Django 3.2.21 on 2023-10-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20231023_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojimodel',
            name='emoji_url',
            field=models.TextField(),
        ),
    ]
