# Generated by Django 3.2.21 on 2023-10-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_emojimodel_emoji_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emojimodel',
            old_name='emoji_url',
            new_name='emoji_colon_name',
        ),
        migrations.RemoveField(
            model_name='emojimodel',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='emojimodel',
            name='object_id',
        ),
        migrations.AddField(
            model_name='channelposts',
            name='emojis',
            field=models.ManyToManyField(to='home.EmojiModel'),
        ),
        migrations.AddField(
            model_name='postcomments',
            name='emojis',
            field=models.ManyToManyField(to='home.EmojiModel'),
        ),
    ]
