# Generated by Django 3.2.21 on 2023-10-24 09:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20231023_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojimodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='emojimodel',
            name='users_who_incremented',
            field=models.ManyToManyField(blank=True, related_name='emojimodel_incremented', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emojimodel',
            name='emoji_colon_name',
            field=models.TextField(unique=True),
        ),
    ]
