# Generated by Django 3.2.21 on 2023-10-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20231024_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emojimodel',
            name='emoji_colon_name',
            field=models.TextField(),
        ),
    ]
