# Generated by Django 3.2.21 on 2023-10-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_emojimodel_emoji_colon_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emojimodel',
            name='count',
        ),
    ]
