# Generated by Django 3.2.21 on 2023-10-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_userpoststatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoststatus',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.channelposts'),
        ),
    ]
