# Generated by Django 3.2.21 on 2023-10-26 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_userpoststatus_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPostStatus',
        ),
    ]
