# Generated by Django 3.2.21 on 2023-11-23 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messaging', '0003_alter_unreadmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emojimodel',
            name='incremented_by',
            field=models.ManyToManyField(blank=True, related_name='emojimodel_incremented_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='message',
            name='images',
        ),
        migrations.AddField(
            model_name='message',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
