# Generated by Django 3.2.21 on 2023-10-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_channel',
            field=models.IntegerField(default=0),
        ),
    ]
