# Generated by Django 3.2.21 on 2023-10-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_last_viewed_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_viewed_channel',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
