# Generated by Django 3.2.21 on 2023-10-06 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20231004_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_viewed_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_viewed_channel_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
