# Generated by Django 3.2.21 on 2023-09-24 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channelmodel',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='channelmodel',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='channelmodel',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
