# Generated by Django 3.2.21 on 2023-09-25 10:02

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_channelposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelposts',
            name='post',
            field=django_summernote.fields.SummernoteTextField(default=''),
        ),
    ]
