# Generated by Django 3.2.21 on 2023-09-27 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('channels', '0004_alter_channelposts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmodel',
            name='users',
            field=models.ManyToManyField(related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
