# Generated by Django 3.2.21 on 2023-09-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_channelmodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelposts',
            name='post',
            field=models.TextField(),
        ),
    ]
